'use strict';

exports.up = function(knex) {
  return knex('users')
    .insert({
      first_name: 'Jamieson',
      last_name: 'Bates',
      email: 'jamiesonbates@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Chris',
      last_name: 'Metz',
      email: 'chrismetz@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Emile',
      last_name: 'Fleming',
      email: 'emilefleming@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Dylan',
      last_name: 'vu',
      email: 'dylanvu@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Brian',
      last_name: 'Lee',
      email: 'brianlee@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Mike',
      last_name: 'Friedman',
      email: 'mikefriedman@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Hiromi',
      last_name: 'Heider',
      email: 'hiromiheider@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Minh',
      last_name: 'Chau',
      email: 'minhchau@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Will',
      last_name: 'Helton',
      email: 'willhelton@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Dan',
      last_name: 'Pencak',
      email: 'danpencak@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Paul',
      last_name: 'Miller',
      email: 'paulmiller@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Siyami',
      last_name: 'Avci',
      email: 'siyamiavci@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Jake',
      last_name: 'Bell',
      email: 'jakebell@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Ryan',
      last_name: 'Sobol',
      email: 'ryansobol@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Roger',
      last_name: 'Schmidt',
      email: 'rogerschmidt@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    }, {
      first_name: 'Scott',
      last_name: 'Hurlow',
      email: 'scotthurlow@beerista.com',
      city: 'Seattle',
      state: 'WA',
      hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
    })
    .then(() => {
      return knex.raw("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));");
    });
}
