'use strict';

exports.seed = function(knex) {
  return knex('users').del()
    .then(() => {
      return knex('users')
        .insert([{
          id: 1,
          first_name: 'Jamieson',
          last_name: 'Bates',
          email: 'jamiesonbates@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 2,
          first_name: 'Chris',
          last_name: 'Metz',
          email: 'chrismetz@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 3,
          first_name: 'Emile',
          last_name: 'Fleming',
          email: 'emilefleming@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 4,
          first_name: 'Dylan',
          last_name: 'vu',
          email: 'dylanvu@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 5,
          first_name: 'Brian',
          last_name: 'Lee',
          email: 'brianlee@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 6,
          first_name: 'Mike',
          last_name: 'Friedman',
          email: 'mikefriedman@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 7,
          first_name: 'Hiromi',
          last_name: 'Heider',
          email: 'hiromiheider@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 8,
          first_name: 'Minh',
          last_name: 'Chau',
          email: 'minhchau@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 9,
          first_name: 'Will',
          last_name: 'Helton',
          email: 'willhelton@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 10,
          first_name: 'Dan',
          last_name: 'Pencak',
          email: 'danpencak@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 11,
          first_name: 'Paul',
          last_name: 'Miller',
          email: 'paulmiller@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 12,
          first_name: 'Siyami',
          last_name: 'Avci',
          email: 'siyamiavci@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 13,
          first_name: 'Jake',
          last_name: 'Bell',
          email: 'jakebell@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 14,
          first_name: 'Ryan',
          last_name: 'Sobol',
          email: 'ryansobol@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 15,
          first_name: 'Roger',
          last_name: 'Schmidt',
          email: 'rogerschmidt@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }, {
          id: 16,
          first_name: 'Scott',
          last_name: 'Hurlow',
          email: 'scotthurlow@beerista.com',
          city: 'Seattle',
          state: 'WA',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS'
        }])
        .then(() => {
          return knex.raw("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));");
        });
    });
};
